import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${robotoCondensed.className} antialiased`}>
      <body className="w-screen flex justify-center">
        <div className="w-full max-w-160 lg:max-w-5xl min-h-screen flex flex-col items-center px-4">
          <Header />
          <div className="flex-1 w-full">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
